### ISSUE TITLE
is it SAM/BAM format? Consider opening with check_sq=False

### ISSUE THREAD

**Issue by nbutyrate** [snayfach/IGGsearch#28]
HI i am trying to run IGGsearch, following is the workflow and error

run_iggsearch.py search --m1 test.fastq.gz --outdir test --test 

Warning: this is a quick test run; results should not be interpreted

## Initializing database
  total species: 4558
  total genes: 100000
  module: 0.9 seconds, program: 0.9 seconds, peak RAM: 0.08 GB

## Aligning reads
  running: bowtie2 --no-unal -q -x /data/ubuntu/ALL_FASTQ_FASTAs/IGGsearch/iggdb_v1.0.0_gut/iggdb_v1.0.0_gut -u 1000 --threads 1 -U test.fastq.gz | samtools view -b - --threads 1 | samtools sort - --threads 1 -O BAM > test/mapped_reads.bam 
  module: 11.68 seconds, program: 12.58 seconds, peak RAM: 1.78 GB

## Counting mapped reads
Traceback (most recent call last):
  File "/data/ubuntu/ALL_FASTQ_FASTAs/IGGsearch/run_iggsearch.py", line 28, in <module>
    search.main()
  File "/data/ubuntu/ALL_FASTQ_FASTAs/IGGsearch/iggsearch/search.py", line 382, in main
    count_reads_bt2(args, db)
  File "/data/ubuntu/ALL_FASTQ_FASTAs/IGGsearch/iggsearch/search.py", line 269, in count_reads_bt2
    bamfile = pysam.AlignmentFile(bam_path, "r")
  File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 985, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

**Comment by nbutyrate** [comment]
please avoid, i have sorted it out

**Comment by JiaZhong28** [comment]
hi, I've gotten the same error and i wonder how you sovle the problems, thx.

**Comment by ice4prince** [comment]
hi, I've gotten the same error and I also wonder how you solve the problems, thx.

**Comment by ice4prince** [comment]
> please avoid, i have sorted it out

Hi, may I ask how you sorted it out?
