### ISSUE TITLE
Make possible to install using pip or conda

### ISSUE THREAD

**Issue by boulund** [snayfach/IGGsearch#30]
Are there any plans to make the tool installable via pip or conda?

**Comment by boulund** [comment]
Just noticed that the install instructions in the README are incorrect. They currently state:

> Clone the repo from github: `git clone https://github.com/snayfach/IGGsearch`
> 
> Update your environment:
> `export PYTHONPATH=$PYTHONPATH:/path/to/IGGsearch`
> `export PATH=$PATH:/path/to/IGGsearch`

But following these instructions leads to:
```
Traceback (most recent call last):
  File "IGGsearch/run_iggsearch.py", line 30, in <module>
    from iggsearch import download
  File "/home/analyses/06.iggsearch_test_20190730_FB/IGGsearch/iggsearch/download.py", line 3, in <module>
    import os, sys, subprocess as sp, numpy as np, time, shutil, utility
ModuleNotFoundError: No module named 'utility'
```

The correct instruction should probably be `export PYTHONPATH=$PYTHONPATH:/path/to/IGGsearch/iggsearch`.  This would of course not be a problem if the package was installable via pip or conda.

**Comment by snayfach** [comment]
Yes of course, thank you! That will be fixed shortly. 

There are not currently any plans to make the tool available via pip/conda, but I agree that would be a good thing. I'll look into it if I find the time and will leave the ticket open while that issue remains.
